name: votefromhome
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rounded_loading_button:
  tab_indicator_styler:
  dio:
  flutter_login:
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  lottie:
  provider: ^5.0.0
  http:
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.4
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.6
  dotted_border: ^2.0.0
  platform_action_sheet: ^0.0.3
  image_picker: ^0.7.4
  circular_countdown: ^2.0.0
  fancy_timer: ^2.0.0
  auto_animated: ^3.0.0
  alert_dialog: ^1.0.0
  dart_ipify: ^1.1.0
  rflutter_alert: ^2.0.2
  bip39: ^1.0.6
  google_fonts: ^2.0.0
  shared_preferences: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
  
 